import React,{useEffect,useRef,useState} from "react";
import {exportModel,loadModel,compressModel,browserSupportedOutputs} from "./engine.js";
import ModelCanvas from "./ModelCanvas.jsx";
import {Link,NavLink,Route,Routes,useParams} from "react-router-dom";
const formats=[["step","STEP","STEP CAD"],["stp","STP","STEP CAD"],["sldprt","SLDPRT","SolidWorks Part"],["sldasm","SLDASM","SolidWorks Assembly"],["slddrw","SLDDRW","SolidWorks Drawing"],["obj","OBJ","Wavefront OBJ"],["fbx","FBX","Autodesk FBX"],["stl","STL","Stereolithography"],["gltf","GLTF","glTF"],["glb","GLB","glTF Binary"],["usd","USD","Universal Scene Description"],["usda","USDA","Universal Scene Description"],["usdc","USDC","Universal Scene Description"],["usdz","USDZ","Universal Scene Description"],["3dm","3DM","Rhino"],["max","MAX","3ds Max"],["blend","BLEND","Blender"],["skp","SKP","SketchUp"],["dae","DAE","COLLADA"],["dwg","DWG","AutoCAD DWG"],["dxf","DXF","AutoCAD DXF"],["3ds","3DS","3ds Max"],["iges","IGES","IGES"],["igs","IGS","IGES"],["ply","PLY","Stanford PLY"],["vox","VOX","MagicaVoxel"],["mdl","MDL","Game Model"],["3mf","3MF","3D Manufacturing"],["brep","BREP","Boundary Representation"],["smd","SMD","Valve Model"],["lwo","LWO","LightWave"],["bvh","BVH","Biovision"],["x","X","DirectX"],["rbxm","RBXM","Roblox Model"],["rbxl","RBXL","Roblox Level"],["b3d","B3D","Blitz3D"],["off","OFF","Object File Format"],["md3","MD3","Quake III"],["ase","ASE","3ds Max ASE"],["scn","SCN","Scene"],["md2","MD2","Quake II"],["ac3d","AC3D","AC3D"],["ac","AC","AC3D"],["ms3d","MS3D","MilkShape"],["cob","COB","TrueSpace"],["vta","VTA","Valve Animation"],["raw","RAW","Raw Model"],["ter","TER","Terragen"],["hmb","HMB","TrueSpace HMB"],["xgl","XGL","XGL"],["zgl","ZGL","XGL"],["lws","LWS","LightWave Scene"],["csm","CSM","CharacterStudio Motion"],["irrmesh","IRRMESH","Irrlicht Mesh"],["irr","IRR","Irrlicht Scene"],["iqm","IQM","Inter-Quake"],["mdc","MDC","Wolfenstein"],["md5","MD5","Doom 3"],["m3d","M3D","Model 3D"],["ogex","OGEX","OpenGEX"],["x3d","X3D","Extensible 3D"],["q3s","Q3S","Quick3D"],["nff","NFF","Neutral File"],["ndo","NDO","Nendo"],["amf","AMF","Additive Manufacturing File Format"],["ifc","IFC","Industry Foundation Classes"],["gcode","GCODE","G-Code"],["nc","NC","Numerical Control"],["3d","3D","Unreal 3D"],["xml","XML","Mesh XML"],["acc","ACC","ACC"],["amj","AMJ","AMJ"],["ask","ASK","ASK"],["enff","ENFF","ENFF"],["mot","MOT","Motion"],["pmx","PMX","MikuMikuDance"],["prj","PRJ","Project Model"],["q3o","Q3O","Quick3D"],["sib","SIB","SIB"],["uc","UC","UC"],["lxo","LXO","Modo"]];
const pairs=[["step","obj"],["step","stl"],["stl","glb"],["obj","fbx"],["fbx","glb"],["ifc","stl"],["dwg","dxf"],["blend","glb"],["skp","obj"],["3dm","obj"]];
const label=k=>formats.find(x=>x[0]===k)?.[1]||String(k||"").toUpperCase();
function Header(){const links=[["/convert","Convert"],["/compress","Compress"],["/render-model","Render"],["/view","View"],["/pricing","Pricing"]];return <header className="header"><div className="wrap nav"><Link className="brand" to="/"><span className="logo">◈</span>Convert<span className="muted">3D</span></Link><nav>{links.map(([p,t])=><NavLink key={p} to={p} className={({isActive})=>isActive?"navlink active":"navlink"}>{t}</NavLink>)}</nav><div className="nav-actions"><Link className="subtle-link" to="/developer-api">API</Link><Link className="btn small primary" to="/image-to-3d">Image to 3D</Link></div></div></header>}
function Footer(){return <footer className="footer"><div className="wrap footer-grid"><div><Link className="brand" to="/"><span className="logo">◈</span>Convert<span className="muted">3D</span></Link><p>3D tools for the browser.</p></div><div><b>Company</b><Link to="/posts">Blog</Link><Link to="/about">About</Link></div><div><b>Tools & API</b><Link to="/convert">Convert</Link><Link to="/compress">Compress</Link><Link to="/render-model">Render</Link><Link to="/view">View</Link><Link to="/developer-api">Developer API</Link></div><div><b>Legal</b><Link to="/about/privacy">Privacy</Link><Link to="/about/terms">Terms</Link></div></div><div className="wrap copyright">© 2026 Convert3D</div></footer>}
function Hero({title,subtitle,children}){return <section className="hero"><div className="wrap hero-inner"><div className="eyebrow">3D WORKFLOWS · BROWSER FIRST</div><h1>{title}</h1><p>{subtitle}</p>{children}</div></section>}
function Uploader({accept,onFiles,labelText="Select 3D model files"}){const ref=useRef(null);const [drag,setDrag]=useState(false);const add=f=>{const a=[...f];if(a.length)onFiles(a)};return <div className={"uploader "+(drag?"drag":"")} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);add(e.dataTransfer.files)}}><input hidden ref={ref} type="file" multiple accept={accept||formats.map(f=>"."+f[0]).join(",")} onChange={e=>add(e.target.files)}/><div className="upload-icon">↑</div><h3>{labelText}</h3><p>or drop files here</p><button className="btn primary" onClick={()=>ref.current?.click()}>Choose files</button><div className="privacy-pill">✓ Privacy-aware workflow</div></div>}
function useSEO(title,description){useEffect(()=>{document.title=title;let m=document.querySelector('meta[name="description"]');if(!m){m=document.createElement("meta");m.name="description";document.head.appendChild(m)}m.content=description;},[title,description])}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function serverConvert(file,output){
  const form=new FormData();form.append("file",file,file.name);form.append("output",output);
  const response=await fetch("/api/convert",{method:"POST",body:form});
  if(!response.ok) throw new Error((await response.json().catch(()=>({}))).error||"Server conversion is unavailable.");
  return new Blob([await response.arrayBuffer()],{type:response.headers.get("content-type")||"application/octet-stream"});
}
function Converter({from,to}){
  const [files,setFiles]=useState([]);const [out,setOut]=useState(to||"obj");const [busy,setBusy]=useState(false);const [object,setObject]=useState(null);const [engine,setEngine]=useState("");const [error,setError]=useState("");const [done,setDone]=useState(0);
  const selectFiles=async next=>{setFiles(next);setDone(0);setError("");setObject(null);setEngine("");if(next[0]){try{const r=await loadModel(next[0]);setObject(r.object);setEngine(r.engine)}catch(e){setError(e?.message||"Unable to read this file.")}}};
  const run=async()=>{if(!files.length)return;setBusy(true);setError("");setDone(0);try{for(const file of files){const ext=file.name.split(".").pop()?.toLowerCase()||"";if(ext===out){downloadBlob(file,file.name);setDone(n=>n+1);continue}try{const r=object&&files[0]===file?{object,source:ext,engine}:await loadModel(file);const result=await exportModel(r.object,out);const base=file.name.replace(/\.[^.]+$/,"");downloadBlob(result.blob,base+"."+result.ext);setDone(n=>n+1)}catch(localError){const blob=await serverConvert(file,out);const base=file.name.replace(/\.[^.]+$/,"");downloadBlob(blob,base+"."+out);setDone(n=>n+1)}}}catch(e){setError(e?.message||"Conversion failed.")}finally{setBusy(false)}};
  return <div className="card converter">
    <div className="converter-head"><div><b>{from?label(from):"Any 3D model"}</b><span>→</span><b>{label(out)}</b></div><span className="tiny">{engine||"Browser conversion engine"}</span></div>
    <Uploader onFiles={selectFiles}/>
    {object&&<ModelCanvas object={object}/>}
    {files.length>0&&<div className="file-list">{files.map((f,i)=><div className="file-row" key={f.name+i}><div><b>{f.name}</b><span>{(f.size/1048576).toFixed(2)} MB</span></div><button className="icon-btn" onClick={()=>selectFiles(files.filter((_,n)=>n!==i))}>×</button></div>)}</div>}
    <div className="converter-controls"><label>Output format<select value={out} onChange={e=>setOut(e.target.value)}>{formats.slice(0,30).map(f=><option key={f[0]} value={f[0]}>{f[1]} — {f[2]}{browserSupportedOutputs.includes(f[0])?" · Browser":" · Engine/API"}</option>)}</select></label><button className="btn primary" disabled={!files.length||busy} onClick={run}>{busy?"Converting…":done===files.length&&done>0?"Download again":"Convert"}</button></div>
    {error&&<div className="error-box">{error}</div>}{done>0&&done===files.length&&!error&&<div className="success">✓ {done} file{done>1?"s":""} converted and downloaded.</div>}
  </div>
}
function Home(){useSEO("Convert 3D models online - Free 3D Model Converter","Convert 3D models online for free. Convert STEP, STL, OBJ, FBX, GLB and more with browser-based tools.");return <><Hero title="Convert 3D models online" subtitle="Convert, compress, render and inspect 3D files from one clean workspace."><div className="hero-actions"><Link className="btn primary" to="/convert">Start converting</Link><Link className="btn" to="/view">Open viewer</Link></div></Hero><main className="wrap main"><section className="grid-2"><div><h2>Everything for your 3D workflow</h2><p className="lead">A focused toolkit for creators, CAD teams and realtime projects.</p><div className="feature-grid">{[["↔","Convert","Move between CAD, mesh and realtime formats.","/convert"],["◌","Compress","Reduce model weight for sharing and web delivery.","/compress"],["◇","Render","Create quick previews and polished visuals.","/render-model"],["◫","View","Inspect 3D assets without desktop software.","/view"]].map(([i,t,d,p])=><Link className="feature-card" to={p} key={t}><span className="ficon">{i}</span><div><h3>{t}</h3><p>{d}</p></div></Link>)}</div></div><Converter/></section><section className="section"><div className="section-head"><div><h2>Popular conversions</h2><p>Jump directly into common format pairs.</p></div><Link to="/convert">Browse all →</Link></div><div className="pair-grid">{pairs.map(([a,b])=><Link className="pair-card" key={a+b} to={"/"+a+"-to-"+b}><span>{label(a)}</span><span className="arrow">→</span><span>{label(b)}</span></Link>)}</div></section><section className="stats"><div><b>70+</b><span>formats cataloged</span></div><div><b>1,000+</b><span>possible combinations</span></div><div><b>0</b><span>desktop installs</span></div><div><b>24/7</b><span>web access</span></div></section><section className="section faq"><h2>Frequently asked questions</h2>{[["What is Convert3D?","A browser-first interface for common 3D file workflows."],["Are files private?","The UI is designed for privacy-aware processing. Connect a local WASM engine or a server processor according to your deployment."],["Which formats are available?","The catalog contains CAD, mesh, scene, animation and game-oriented formats."]].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section></main></>}
function Convert(){useSEO("3D Model Converter Online - Convert3D","Free online 3D model converter. Convert popular CAD, mesh and realtime 3D formats.");return <><Hero title="3D model converter" subtitle="Convert 3D models between CAD, mesh, scene and realtime formats online."><Converter/></Hero><main className="wrap main"><h2>Supported file formats</h2><div className="format-cloud">{formats.map(f=><Link key={f[0]} to={"/convert/"+f[0]}>{f[1]}</Link>)}</div></main></>}
function FormatPage(){const {format}=useParams();const name=label(format);useSEO(name+" Converter Online (Free)","Convert "+name+" 3D model files online. No sign up required. Browse conversion options and preview your model.");return <><Hero title={name+" converter"} subtitle={"A focused conversion page for "+(formats.find(f=>f[0]===format)?.[2]||"3D")+" files."}><Converter from={format}/></Hero><main className="wrap main"><section className="grid-2"><div><h2>About {name}</h2><p>{name} is used across many 3D workflows. Pick a destination format that matches your application and verify geometry, units, materials and metadata after export.</p></div><div className="card"><h3>Common outputs</h3><div className="chip-list">{formats.slice(0,18).filter(f=>f[0]!==format).map(f=><Link key={f[0]} to={"/"+format+"-to-"+f[0]}>{name} → {f[1]}</Link>)}</div></div></section></main></>}
function Pair(){const {pair}=useParams();const raw=String(pair||"");const [from,to]=raw.split("-to-");const source=label(from);const target=label(to);useSEO(source+" to "+target+" Converter Online (Free)","Convert "+source+" to "+target+" online for free. No sign up required.");return <><Hero title={source+" to "+target+" Converter"} subtitle={"Convert "+source+" "+raw+" 3D file to "+target+" for free. No sign up or credit card required."}><Converter from={from} to={to}/></Hero><main className="wrap main"><section className="grid-2"><div><h2>Convert {source} to {target}</h2><p>Convert a {source} model into {target} with a browser-first workflow. After conversion, check geometry, units, materials, textures and metadata in the destination application.</p></div><div className="card"><h3>Compatibility</h3><ul className="checklist"><li>Geometry</li><li>Scale and units</li><li>Materials and textures</li><li>Metadata and names</li></ul></div></section></main></>}
function ViewerPanel({renderMode=false}){const [files,setFiles]=useState([]);const [object,setObject]=useState(null);const [error,setError]=useState("");const [wireframe,setWireframe]=useState(false);const [capture,setCapture]=useState(null);const choose=async list=>{setFiles(list);setError("");setObject(null);setCapture(null);try{if(list[0]){const r=await loadModel(list[0]);setObject(r.object)}}catch(e){setError(e?.message||"Unable to load this model.")}};const save=()=>{if(!capture)return;const a=document.createElement("a");a.href=capture();a.download=(files[0]?.name||"model").replace(/\.[^.]+$/,"")+".png";a.click()};return <div className="card tool-panel"><Uploader onFiles={choose}/>{object&&<><ModelCanvas object={object} wireframe={wireframe} onReady={setCapture}/><div className="tool-actions">{!renderMode&&<button className="btn" onClick={()=>setWireframe(v=>!v)}>{wireframe?"Solid mode":"Wireframe"}</button>}{renderMode&&<button className="btn primary" onClick={save}>Download PNG</button>}</div></>}{error&&<div className="error-box">{error}</div>}</div>}
function Tool({kind}){useSEO(kind==="compress"?"3D Model Compressor":kind==="render"?"3D Model Renderer":"3D Model Viewer","Free browser-first 3D tool for viewing, rendering and optimizing model files.");if(kind==="compress"){return <><Hero title="Compress 3D Models Online" subtitle="Reduce mesh complexity and export a compact GLB directly in your browser."><CompressPanel/></Hero><main className="wrap main"><section className="section"><h2>Browser compression</h2><p className="lead">The compressor simplifies large mesh geometries and exports the result as GLB. Original files remain untouched.</p></section></main></>}if(kind==="view")return <><Hero title="3D Model Viewer" subtitle="View 3D models online with orbit controls, material preview and wireframe mode."><ViewerPanel/></Hero><main className="wrap main"><div className="steps">{["Upload a model","Inspect in 3D","Toggle wireframe","Review materials"].map((s,i)=><div className="step" key={s}><span>{i+1}</span><b>{s}</b><p>Everything stays in the browser for supported formats.</p></div>)}</div></main></>;return <><Hero title="3D Model Renderer" subtitle="Turn your 3D model into a PNG preview with local browser rendering."><ViewerPanel renderMode/></Hero><main className="wrap main"><section className="section"><h2>As-is rendering</h2><p className="lead">Upload a supported model, inspect framing and download a PNG snapshot.</p></section></main></>}

function CompressPanel(){const [files,setFiles]=useState([]);const [object,setObject]=useState(null);const [quality,setQuality]=useState("balanced");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [result,setResult]=useState(null);const choose=async list=>{setFiles(list);setError("");setResult(null);setObject(null);try{if(list[0]){const r=await loadModel(list[0]);setObject(r.object)}}catch(e){setError(e?.message||"Unable to read this model.")}};const run=async()=>{if(!object)return;setBusy(true);setError("");setResult(null);try{const r=await compressModel(object,quality);setResult(r)}catch(e){setError(e?.message||"Compression failed.")}finally{setBusy(false)}};return <div className="card tool-panel"><Uploader onFiles={choose}/>{object&&<ModelCanvas object={object}/>}<div className="converter-controls"><label>Compression level<select value={quality} onChange={e=>setQuality(e.target.value)}><option value="high">High quality</option><option value="balanced">Balanced</option><option value="small">Smaller file</option></select></label><button className="btn primary" disabled={!object||busy} onClick={run}>{busy?"Compressing…":"Compress to GLB"}</button></div>{error&&<div className="error-box">{error}</div>}{result&&<div className="success">✓ Compressed GLB ready. <button className="link-button" onClick={()=>{const a=document.createElement("a");a.href=URL.createObjectURL(result.blob);a.download=(files[0]?.name||"model").replace(/\.[^.]+$/,"")+".glb";a.click()}}>Download</button></div>}</div>}
function ImageTo3D(){const [img,setImg]=useState(null);const [quality,setQuality]=useState("balanced");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [result,setResult]=useState(null);const generate=async()=>{if(!img)return;setBusy(true);setError("");setResult(null);try{const form=new FormData();form.append("file",img,img.name);form.append("quality",quality);const r=await fetch("/api/image-to-3d",{method:"POST",body:form});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||"Image-to-3D provider is unavailable.");const blob=new Blob([await r.arrayBuffer()],{type:r.headers.get("content-type")||"application/octet-stream"});setResult(blob)}catch(e){setError(e?.message||"Generation failed.")}finally{setBusy(false)}};return <><Hero title="Image to 3D" subtitle="Turn a reference image into a starting-point 3D asset workflow."><div className="card"><Uploader accept="image/*" labelText="Select a reference image" onFiles={f=>{setImg(f[0]);setError("");setResult(null)}}/>{img&&<div className="success">✓ Ready: {img.name}</div>}<div className="converter-controls"><label>Quality<select value={quality} onChange={e=>setQuality(e.target.value)}><option value="fast">Fast</option><option value="balanced">Balanced</option><option value="high">High detail</option></select></label><button className="btn primary" disabled={!img||busy} onClick={generate}>{busy?"Generating…":"Generate 3D"}</button></div>{error&&<div className="error-box">{error}</div>}{result&&<div className="success">✓ 3D result ready. <button className="link-button" onClick={()=>downloadBlob(result,(img?.name||"model").replace(/\.[^.]+$/,"")+".glb")}>Download model</button></div>}</div></Hero><main className="wrap main"><div className="grid-3">{["Reference","AI generation","Preview"].map((x,i)=><div className="card mini" key={x}><span className="num">{i+1}</span><h3>{x}</h3><p>{i===1?"Requires a configured Image-to-3D provider.":"Clear stages for an image-to-3D pipeline."}</p></div>)}</div></main></>}

function Pricing(){const plans=[["Free","$0",["Core tools","Limited processing","Browser viewer","Community support"]],["Pro","$19",["Higher limits","Priority processing","Batch workflows","Commercial projects"]],["API","Usage based",["REST API","Async jobs","Upload URLs","Usage monitoring"]]];return <><Hero title="Pricing" subtitle="Start with browser tools, then scale when your workflow needs more capacity."/><main className="wrap main"><div className="pricing-grid">{plans.map(([n,p,it])=><div className="card price" key={n}><h2>{n}</h2><div className="price-val">{p}</div><ul className="checklist">{it.map(x=><li key={x}>{x}</li>)}</ul><Link className="btn primary" to={n==="API"?"/developer-api":"/convert"}>Get started</Link></div>)}</div></main></>}
function API(){return <><Hero title="Developer API" subtitle="Use the same conversion service from your own application."/><main className="wrap main"><section className="grid-2"><div className="card"><h3>POST /api/convert</h3><pre>multipart/form-data
file = model.step
output = obj</pre><p className="lead">The endpoint proxies to the provider configured with CONVERTER_API_URL.</p></div><div><h2>Health check</h2><p className="lead">GET /api/health reports whether the conversion and Image-to-3D providers are configured.</p><Link className="btn" to="/api/health">Open health endpoint</Link></div></section></main></>}
const posts=[["dwg-solid","From DWG to solid workflows"],["blender-gltf","Blender to glTF for the web"],["glb-size","How to reduce GLB size"],["sharing-3d","Sharing 3D models safely"]];
function Posts(){return <><Hero title="3D workflow guides" subtitle="Practical notes about formats, conversion, viewing and delivery."/><main className="wrap main"><div className="post-grid">{posts.map(([s,t])=><Link className="post-card" to={"/posts/"+s} key={s}><div className="post-kicker">Guide</div><h3>{t}</h3><p>Practical guidance for a common 3D workflow.</p><span>Read article →</span></Link>)}</div></main></>}
function Post(){const {slug}=useParams();const p=posts.find(x=>x[0]===slug)||posts[0];return <main className="wrap article"><div className="eyebrow">GUIDE</div><h1>{p[1]}</h1><p className="lead">A practical note for creators working across multiple 3D tools and formats.</p><p>Choose the format based on the final software or delivery target. After conversion, inspect geometry, scale, materials, textures and metadata rather than assuming every feature maps perfectly between formats.</p><h2>Suggested workflow</h2><ol><li>Keep an untouched source copy.</li><li>Choose a destination based on the actual target application.</li><li>Preview the result before distribution.</li><li>Record important settings for repeatable exports.</li></ol></main>}
function All(){return <><Hero title="All 3D conversion paths" subtitle="Browse the format catalog and jump directly to a conversion workflow."/><main className="wrap main"><div className="format-cloud">{formats.map(f=><Link key={f[0]} to={"/convert/"+f[0]}>{f[1]} Converter</Link>)}</div><section className="section"><h2>Popular pairs</h2><div className="pair-grid">{pairs.map(([a,b])=><Link className="pair-card" key={a+b} to={"/"+a+"-to-"+b}>{label(a)} → {label(b)}</Link>)}</div></section></main></>}
function About(){const {section}=useParams();if(section==="privacy")return <main className="wrap article"><div className="eyebrow">LEGAL</div><h1>Privacy</h1><p>Use this page to document how uploads, processing, analytics and third-party services are handled by your deployment. Keep it aligned with the actual implementation.</p><h2>Data handling</h2><p>Explain whether processing happens locally, on your server or through an external processing provider. State retention and deletion behavior clearly.</p></main>;if(section==="terms")return <main className="wrap article"><div className="eyebrow">LEGAL</div><h1>Terms</h1><p>Use of the service is subject to the limits and policies shown by the deployed application.</p><h2>Acceptable use</h2><p>Do not upload files you do not have permission to process. Keep backups of original production assets.</p></main>;return <><Hero title="About Convert3D" subtitle="A browser-first toolkit for common 3D asset workflows."/><main className="wrap main"><section className="grid-2"><div><h2>One place for the workflow</h2><p>Conversion, compression, rendering, viewing, image-to-3D and developer tooling share one consistent navigation model.</p></div><div className="card"><h3>Principles</h3><ul className="checklist"><li>Clear format intent</li><li>Privacy-aware processing</li><li>Fast interfaces</li><li>Useful documentation</li></ul></div></section><section className="section"><h2>Legal</h2><div className="legal-links"><Link to="/about/privacy">Privacy</Link><Link to="/about/terms">Terms</Link></div></section></main></>}
function NotFound(){return <main className="wrap article"><h1>Page not found</h1><Link className="btn primary" to="/">Back home</Link></main>}
export default function App(){return <div className="app"><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/convert" element={<Convert/>}/><Route path="/all" element={<All/>}/><Route path="/convert/:format" element={<FormatPage/>}/><Route path="/:pair/app" element={<Pair/>}/><Route path="/:pair" element={<Pair/>}/><Route path="/compress" element={<Tool kind="compress"/>}/><Route path="/render-model" element={<Tool kind="render"/>}/><Route path="/view" element={<Tool kind="view"/>}/><Route path="/image-to-3d" element={<ImageTo3D/>}/><Route path="/pricing" element={<Pricing/>}/><Route path="/developer-api" element={<API/>}/><Route path="/posts" element={<Posts/>}/><Route path="/posts/:slug" element={<Post/>}/><Route path="/about/:section?" element={<About/>}/><Route path="*" element={<NotFound/>}/></Routes><Footer/></div>}